### PR TITLE
Add WalletLink support

### PR DESCRIPTION
**Pull request by vishnumad**
This PR adds support for WalletLink / Coinbase Wallet
* Adds a new WalletLink connecter
* Updates the existing Coinbase logo
* Updates example project to use WalletLink 

Screen Shot 2021-04-30 at 3 42 53 PM

### CODE REVIEW

**Review by hieronymus777 — APPROVED** [review]

**Comment by brantlymillegan** [comment]
hey @pedrouid would love to get this merged so we can use it on the ENS Manager app. Something specific blocking it?

**Comment by spencerstock** [comment]
Still hoping to see this merged.

**Comment by kkagill** [comment]
please merge this one!

**Comment by bf6** [comment]
Need this also - can we merge?

**Comment by jafri** [comment]
@pedrouid could you kindly have a look

**Comment by julien51** [comment]
@pedrouid I understand the pain here, but I think it would be a good example for the community to merge that one...

**Comment by creazy231** [comment]
also need this please 🔥

**Comment by markusbug** [comment]
It would be awesome if this would be merged.

**Comment by afonsosilva91** [comment]
@hieronymus777 any update on this?

**Comment by hieronymus777** [comment]
> @hieronymus777 any update on this?

Hey @afonsosilva91  I would love to see this merge, I'm not an editor on this repo unfortunately.

**Comment by samirspatel** [comment]
@hieronymus777 any idea when this can be merged? huge piled up demand here!

**Comment by afonso-silva-bringglobal** [comment]
@pedrouid can you help here? ⛈

**Comment by afonsosilva91** [comment]
@pedrouid can you help here? ⛈

**Comment by Zettersten** [comment]
bump

**Comment by pedrouid** [comment]
Duplicate #250

**Pull request closed without merging**
