### PR TITLE
Add tally integration

### PR DESCRIPTION
**Pull request by 0xzoz**
Add support for [Tally](https://tally.cash/) wallet. Tally is an open-source browser extension similar to Metamask.

### CODE REVIEW

**Comment by darrenlangley** [comment]
We are very interested in getting this PR merged, if there is anything that needs to happen please let us know.
Many thanks!
@pedrouid

**Comment by martinma612** [comment]
Hope that this PR can be merged as soon as possible. A number of protocols are waiting for it to integrate Tally! Thank you very much!

**Comment by Naxsun** [comment]
Would love to see this added as well. Will open up a whole lot of integration opportunities!

**Comment by xinyang309** [comment]
A lot of integration is in progress. Please we would like to see this done.

**Comment by microHoffman** [comment]
Yes, it would be great to see a support for Tally in Web3Modal!<3

**Pull request merged**
