### PR TITLE
Add binance chain wallet

### PR DESCRIPTION
**Pull request by acryptosx**

### CODE REVIEW

**Review by Godhunter97 — APPROVED** [review]

**Review by Omichaelking — APPROVED** [review]

**Review by Omichaelking — APPROVED** [review]

**Comment by 4skinSkywalker** [comment]
When will this merge into the main source code?

**Review by Connectivewall — APPROVED** [review]

**Comment by grishick** [comment]
When can this be merged? Anything I can do to help move this forward?

**Comment by Connectivewall** [comment]
Yes please I can’t continue, gosh 


Sent from Yahoo Mail for iPhone


On Friday, September 24, 2021, 8:03 PM, Greg Solovyev ***@***.***> wrote:




When can this be merged? Anything I can do to help move this forward?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by rithgan** [comment]
When will this be merged?

**Comment by pmprete** [comment]
Can this be merged please?

**Review by grishick — APPROVED** [review]

**Comment by itxtoledo** [comment]
Hey @pedrouid  what's going on that you don't approve of useful PRs like that? We are in need of them and you do not merge

**Review by pedrouid — APPROVED** [review]

**Pull request merged**
