### PR TITLE
feat: add bitkeep wallet provider

### PR DESCRIPTION
**Pull request by woibldd**

### CODE REVIEW

**Comment by woibldd** [comment]
image

**Comment by keepresolve** [comment]
Excuse me! When will the new version be released?

**Comment by Runzeng** [comment]
What is the installation Provider Options name?

**Comment by Runzeng** [comment]
> Excuse me! When will the new version be released?
'custom-bitkeep-wallet': {
          display: {
            logo: 'bitkeep.png',
            name: 'Bitkeep Wallet',
            description: 'Connect to your Bitkeep Wallet',
          },
          package: true,
          options: {},
          connector: async () => {
            if ((window as any).bitkeep) {
              const bitkeep = (window as any).bitkeep;
              await bitkeep.ethereum.request({ method: 'eth_requestAccounts' });
              return bitkeep.ethereum;
            } else {
              (window as any).open("https://bitkeep.com/download", "_blank");
              throw new Error('No Bitkeep wallet found');
            }
          },
        },

**Comment by Runzeng** [comment]
'custom-bitkeep-wallet': {
          display: {
            logo: 'bitkeep.png',
            name: 'Bitkeep Wallet',
            description: 'Connect to your Bitkeep Wallet',
          },
          package: true,
          options: {},
          connector: async () => {
            if ((window as any).bitkeep) {
              const bitkeep = (window as any).bitkeep;
              await bitkeep.ethereum.request({ method: 'eth_requestAccounts' });
              return bitkeep.ethereum;
            } else {
              (window as any).open("https://bitkeep.com/download", "_blank");
              throw new Error('No Bitkeep wallet found');
            }
          },
        },

**Pull request merged**
