### PR TITLE
add Hardware Wallet support

### PR DESCRIPTION
**Pull request by pedrouid**
* add Ledger connector
* add Trezor connector

### CODE REVIEW

**Comment by pedrouid** [comment]
Available for testing at: https://deploy-preview-117--web3connect.netlify.com/

**Comment by lukasschor** [comment]
@pedrouid What are the steps required to connect a ledger device?
I have my device connected using USB & unlocked. Yet, when I choose the ledger option, the modal just closes without anything happening.

**Comment by pedrouid** [comment]
Hey @lukasschor, unfortunately this is not actually working. The issue is related to the Ledger and Trezor providers themselves which were made custom for web3connect but need to be fixed.

Ledger Provider: https://github.com/web3connect/ledger-provider
Trezor Provider: https://github.com/web3connect/trezor-provider

Alternatively if anyone has knowledge of a better provider implementation for both, please let me know and we can update this PR accordingly

**Comment by jparklev** [comment]
Any updates on this one? Ledger & Trezor seem to not connect at all using those custom providers?

**Comment by kaifaty** [comment]
when hardware wallets will add?

**Comment by tloriato** [comment]
@pedrouid How can I help here? Can you give me some context before I do a deep dive?

**Comment by pedrouid** [comment]
Hi @tloriato, glad you are interested to take this challenge.

To be honest the work needs to be done on a separate repository IMO

The most important thing to consider here is that there needs to be a simple enough provider for both Ledger and Trezor that is compatible with EIP-1193 standard

I've created these under the following repositories but they are not currently working:

Ledger - https://github.com/Web3Modal/ledger-provider
Trezor - https://github.com/Web3Modal/trezor-provider

**Comment by jadbox** [comment]
@pedrouid Is there an update on the Ledger adapter? I commented on the repo, but it seems like it may be abandoned?

**Comment by Dylan-Kerler** [comment]
@pedrouid What's the status on this?

**Comment by microHoffman** [comment]
@pedrouid hello hello, I'd like to ask if there has been any progress on this in the meantime please?:)

**Comment by duxiaofeng-github** [comment]
i need this pls. this issue has been raised for over two years, but you guys just close the pr and delete the branch... at least you can tell me why. i have to switch to web3 onboard now...

**Pull request closed without merging**
